version: '3.8'

services:
  web:
    build: ./web
    command: gunicorn stripe_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
     - ./web:/app
    expose:
      - 8000
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - 80:80
    links:
      - web:web
    depends_on:
      - web