version: '3.8'

services:
  web:
    build: ./web
    command: gunicorn stripe_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
     - static_volume:/static
    expose:
      - 8000
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - "80:80"

    depends_on:
      - web
    volumes:
      - static_volume:/static

volumes:
  static_volume: