# Generated by Django 4.1.6 on 2023-02-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_alter_item_price_tax_order_items_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
